server:  
  port: ${PORT:9040}
  contextPath: /seguridad-entrevista
#  contextPath: /uaa

spring:  
  application:
    name: auth-server

jmx:
  default-domain: auth-server
    
logging:
  level:
    org.springframework.security: TRACE

#security:
#  user:
#    name: root
#    password: password

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ 
#      

#eureka:
#   client:
#    registerWithEureka: false
#    fetchRegistry: false   
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ 