server:  
  port: ${PORT:2003}
#  add
  contextPath: /credito-entrevista

spring:  
  application:
    name: credito-service
#
  jmx:
    default-domain: credito-service
    
#logging:
#  level:
#    account.api.AccountClient: TRACE

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 5
#    lease-expiration-duration-in-seconds: 5
#  client:
#    registerWithEureka: false
#    fetchRegistry: false   
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
            
      
security:
  oauth2:
    resource:
      #loadBalanced: true
#      userInfoUri: http://localhost:9999/uaa/user
      userInfoUri: http://localhost:9040/seguridad-entrevista/user